apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-academic-deployment
  labels:
    app: postgres-academic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-academic
  template:
    metadata:
      labels:
        app: postgres-academic
    spec:
      containers:
        - name: postgres-academic
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER_ACADEMIC
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME_ACADEMIC
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD_ACADEMIC
          volumeMounts:
            - name: postgres-academic-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-academic-storage
          persistentVolumeClaim:
            claimName: postgres-academic-pv-claim
