apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-log-deployment
  labels:
    app: postgres-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-log
  template:
    metadata:
      labels:
        app: postgres-log
    spec:
      containers:
        - name: postgres-log
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER_LOG
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME_LOG
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD_LOG
          volumeMounts:
            - name: postgres-log-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-log-storage
          persistentVolumeClaim:
            claimName: postgres-log-pv-claim
