apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-mahasiswa-deployment
  labels:
    app: postgres-mahasiswa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-mahasiswa
  template:
    metadata:
      labels:
        app: postgres-mahasiswa
    spec:
      containers:
        - name: postgres-mahasiswa
          image: postgres:15-alpine # Gunakan Alpine untuk ukuran image yang lebih kecil
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER_MAHASISWA
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME_MAHASISWA
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: # Gunakan Secret untuk password
                  name: db-credentials
                  key: POSTGRES_PASSWORD_MAHASISWA
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-mahasiswa-pv-claim
