apiVersion: v1
kind: Service
metadata:
  name: academic-service
spec:
  selector:
    app: academic-service
  ports:
    - protocol: TCP
      port: 80 # Port service yang diakses Ingress
      targetPort: 3001 # Port container Academic Service
  type: ClusterIP
