apiVersion: v1
kind: Service
metadata:
  name: mahasiswa-api-service
spec:
  selector:
    app: mahasiswa-api
  ports:
    - protocol: TCP
      port: 80 # Port service yang diakses Ingress
      targetPort: 3000 # Port container Mahasiswa API
  type: ClusterIP # Biasanya ClusterIP jika ada Ingress
