apiVersion: v1
kind: Service
metadata:
  name: postgres-log-service
spec:
  selector:
    app: postgres-log
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30002
  type: NodePort
