apiVersion: v1
kind: Service
metadata:
  name: postgres-mahasiswa-service
spec:
  selector:
    app: postgres-mahasiswa
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30003
  type: NodePort
