apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-mahasiswa-pv-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce # Hanya bisa di-mount oleh satu pod dalam mode read-write
  resources:
    requests:
      storage: 5Gi # Sesuaikan ukuran sesuai kebutuhan
