apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-log-pv-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Sesuaikan ukuran sesuai kebutuhan
