apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pv-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Zookeeper tidak butuh banyak
