apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service-deployment
  labels:
    app: consumer-service
spec:
  replicas: 2 # Untuk horizontal scaling dan ketersediaan
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: execute1d/consumer-service:1.0 # Ganti dengan image Docker Anda
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD # Ambil password dari Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD_LOG
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
